
[Variables]

LocationCode=ae93fc4733f40e71db076c76d48c052418206a1877112b5797347626dc215aa0
URL=https://weather.com/#Language#/weather/today/l/#LocationCode#

Language=en-GB

HourFormat=%H

Ms=
Fm=

TimeFormat=

SizeValue=0.5
SpeedUnit=Mph
PressureUnit=Mb
VisibilityUnit=Mile

FontFaceClock=master of break
FontFaceDate=master of break
FontFaceDate2=master of break
FontFaceWeather=master of break

ClockColorOrig=255,140,0
ClockColorBlack=0,0,0
ClockColor=255,255,255
DayColor=255,255,255
MonthColor=255,255,255
YearColor=255,255,255,200
AMPMColor=255,255,255,170

FontColor=255,255,255
FontColor2=255,255,255,200
FontColor3=191,216,242,255
FontEffectColor=0,0,0,50
Accuracy=2